### ISSUE TITLE
Bottom toolbar container background color

### ISSUE THREAD

**Issue by talenelat-elin** [eustachi0/RemNoteThemes#1]
Amazing theme, as usual!

Small bug i noticed:
![image](https://user-images.githubusercontent.com/71895835/120898172-54a4db80-c647-11eb-8d3f-a3a109fd4bca.png)
The area around the corners of the toolbar is colored white.

The following snippet should fix it. I didn't know where exactly to put it though, so I'm submitting an issue instead of a PR.

```css
#hierarchy-editor-toolbar-container
{background-color: var(--background-color);}
```
