### ISSUE TITLE
No visual indicator when portal is selected.

### ISSUE THREAD

**Issue by talenelat-elin** [eustachi0/RemNoteThemes#3]
I'm back, with another issue. 😆

Basically what the title says.
When you click on the top of a portal, the portal gets selected and you can then delete, copy, or move the entire portal. To indicate the selection in the default theme, the top border turns orange from blue.

But since the portals in your theme don't have borders (which is a feature I absolutely adore), we have no visual indication when the portal is selected.

I tried making something, but it doesn't look very elegant. I'm sure you'll be able to work out something better

![image](https://user-images.githubusercontent.com/71895835/121567347-14c16800-ca3c-11eb-96f9-cffb034dca0c.png)
Here's the css for it:
```css
.portal-rem--selected .portal-rem-top{
	background-color: var(--focused-accent-color);
	border-top-left-radius: var(--border-radius);
	border-top-right-radius: var(--border-radius);
	margin-left: 22px !important;
	margin-right: 13px !important;
}
```
