### ISSUE TITLE
Caret color in latex entry pop-up

### ISSUE THREAD

**Issue by talenelat-elin** [eustachi0/RemNoteThemes#4]
Hi,

Two parts to this one.

1. The color of the LateX entry box (the one which pops up when we type `$$`), seems to be the default theme's colors. Don't know if this is a choice by you or you were unaware of it. Looks good either way, imo.
2. The caret color matches the background, and is not visible at all.

Relevant snippet:
```css
.rich-text-editor__popup-text-editor-latex{
caret-color: auto;
}
```

Cheers, 😄
